# Files and paths to ignore for secret scanning
# OAuth test file contains hardcoded public example secrets
paths-ignore:
  - "src/test/java/com/simisinc/platform/application/oauth/OAuthUserInfoCommandTest.java"
