services:

  db:
    image: ghcr.io/rajkowski/cms-platform-db:15
    env_file:
      .env
    environment:
      POSTGRES_USER: "${DB_USER:?err}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?err}"
    restart: always
    networks:
      - platform
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  app:
    image: ghcr.io/rajkowski/cms-platform:1
    ports:
      - 80:8080
    env_file:
      .env
    environment:
      CMS_ADMIN_USERNAME: "${CMS_ADMIN_USERNAME:?err}"
      CMS_ADMIN_PASSWORD: "${CMS_ADMIN_PASSWORD:?err}"
      CMS_FORCE_SSL: "${CMS_FORCE_SSL:-true}"
      CMS_NODE_TYPE: "${CMS_NODE_TYPE:-main}"
      DB_SERVER_NAME: "${DB_SERVER_NAME:-db}"
      DB_SSL: "${DB_SSL:-false}"
      DB_USER: "${DB_USER:?err}"
      DB_PASSWORD: "${DB_PASSWORD:?err}"
      DB_NAME: "${DB_NAME:-cms-platform}"
    restart: on-failure
    depends_on:
      - db
    networks:
      - platform
    volumes:
      - web-data:/opt/cms-platform:delegated
  
volumes:
  db-data:
  web-data:

networks:
  platform:
