site_name: 'CMS Platform TechDocs'
site_description: 'Developer documentation for CMS Platform'
repo_url: https://github.com/rajkowski/cms-platform
edit_uri: tree/main/docs

# You can test with: npx @techdocs/cli serve
# You must have docker installed and running
plugins:
 - techdocs-core

markdown_extensions:
  - attr_list

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Introduction: 'index.md'
  - Architecture: 'architecture.md'
  - Project Structure: 'project-structure.md'
  - Customization: 'customization.md'
  - Dev Environment: 'developer-environment.md'
  - Installation: 'installation.md'
  - User Guide:
      - Web Page Design User Guide: 'user-guide/web-page-design.md'
  - DevSecOps Pipeline: 'pipeline.md'
  - Integrations:
      - OAuth: 'oauth.md'
  - Decisions: 'decisions.md'
  - Changelog: 'CHANGELOG.md'
