/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.zeroio.platform.infrastructure.persistence.tenant;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.SQLException;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.simisinc.platform.infrastructure.persistence.RepositoryDatabaseTestSupport;
import com.zeroio.platform.domain.model.tenant.WorkspaceSessionHandoffToken;

class WorkspaceSessionHandoffTokenRepositoryTest {

  @BeforeEach
  void setUp() throws SQLException {
    RepositoryDatabaseTestSupport.configureInMemoryH2Database();
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE workspace_session_handoff_tokens ("
            + "workspace_session_handoff_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "token VARCHAR(100) NOT NULL,"
            + "user_id BIGINT NOT NULL,"
            + "workspace_id BIGINT NOT NULL,"
            + "resource VARCHAR(512) NOT NULL,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "consumed_at TIMESTAMP"
            + ")");
  }

  @AfterEach
  void tearDown() {
    RepositoryDatabaseTestSupport.shutdown();
  }

  @Test
  void addAndFindValidByToken_returnsRecord() {
    WorkspaceSessionHandoffToken handoffToken = new WorkspaceSessionHandoffToken();
    handoffToken.setToken("abc-123");
    handoffToken.setMainTenantUserId(42L);
    handoffToken.setWorkspaceId(7L);
    handoffToken.setResource("/dashboard");

    WorkspaceSessionHandoffToken added = WorkspaceSessionHandoffTokenRepository.add(handoffToken);
    assertNotNull(added);
    assertTrue(added.getId() > 0);

    WorkspaceSessionHandoffToken found = WorkspaceSessionHandoffTokenRepository.findValidByToken("abc-123");
    assertNotNull(found);
    assertEquals(42L, found.getMainTenantUserId());
    assertEquals(7L, found.getWorkspaceId());
    assertEquals("/dashboard", found.getResource());
  }

  @Test
  void findValidByToken_returnsNullForUnknownToken() {
    assertNull(WorkspaceSessionHandoffTokenRepository.findValidByToken("does-not-exist"));
  }

  @Test
  void markConsumed_makesTokenInvalid() {
    WorkspaceSessionHandoffToken handoffToken = new WorkspaceSessionHandoffToken();
    handoffToken.setToken("consume-me");
    handoffToken.setMainTenantUserId(1L);
    handoffToken.setWorkspaceId(2L);
    handoffToken.setResource("/");
    WorkspaceSessionHandoffToken added = WorkspaceSessionHandoffTokenRepository.add(handoffToken);

    WorkspaceSessionHandoffTokenRepository.markConsumed(added.getId());

    assertNull(WorkspaceSessionHandoffTokenRepository.findValidByToken("consume-me"));
  }

  @Test
  void findValidByToken_returnsNullForExpiredToken() throws SQLException {
    RepositoryDatabaseTestSupport.executeSql(
        "INSERT INTO workspace_session_handoff_tokens (token, user_id, workspace_id, resource, created) "
            + "VALUES ('expired-token', 1, 2, '/', DATEADD('SECOND', -61, CURRENT_TIMESTAMP))");

    assertNull(WorkspaceSessionHandoffTokenRepository.findValidByToken("expired-token"));
  }
}
