/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.simisinc.platform.infrastructure.persistence.oauth;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.SQLException;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.simisinc.platform.domain.model.login.OAuthToken;
import com.simisinc.platform.infrastructure.persistence.RepositoryDatabaseTestSupport;

class OAuthPersistenceRepositoryTest {

  @BeforeEach
  void setUp() throws SQLException {
    RepositoryDatabaseTestSupport.configureInMemoryH2Database();
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE oauth_tokens ("
            + "token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "user_id BIGINT NOT NULL,"
            + "user_token_id BIGINT NOT NULL,"
            + "provider VARCHAR(255),"
            + "access_token VARCHAR(255),"
            + "token_type VARCHAR(255),"
            + "expires_in INTEGER DEFAULT -1,"
            + "refresh_token VARCHAR(255),"
            + "refresh_expires_in INTEGER DEFAULT -1,"
            + "scope VARCHAR(255),"
            + "expires TIMESTAMP,"
            + "refresh_expires TIMESTAMP,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "enabled BOOLEAN DEFAULT TRUE"
            + ")");
  }

  @AfterEach
  void tearDown() {
    RepositoryDatabaseTestSupport.shutdown();
  }

  @Test
  void oauthTokenRepository_queryAndRemoveWork() throws SQLException {
    RepositoryDatabaseTestSupport.executeSql(
        "INSERT INTO oauth_tokens (user_id, user_token_id, provider, access_token, token_type, expires_in, refresh_token, refresh_expires_in, scope, enabled) VALUES (42, 7, 'github', 'abc', 'bearer', 3600, 'refresh', 7200, 'repo', true)");

    OAuthToken token = OAuthTokenRepository.findByUserTokenId(42L, 7L);
    assertNotNull(token);
    assertEquals("github", token.getProvider());
    assertEquals("abc", token.getAccessToken());

    OAuthToken saved = new OAuthToken();
    saved.setUserId(42L);
    saved.setUserTokenId(8L);
    saved.setProvider("google");
    saved.setAccessToken("def");
    saved.setTokenType("bearer");
    saved.setExpiresIn(3600);
    saved.setRefreshToken("refresh-2");
    saved.setRefreshExpiresIn(7200);
    saved.setScope("openid");
    saved.setEnabled(true);
    OAuthToken added = OAuthTokenRepository.add(saved);
    assertNotNull(added);
    assertEquals(1, OAuthTokenRepository.removeAll(42L));
  }
}
