/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.zeroio.platform.application.login;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.sql.SQLException;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.simisinc.platform.infrastructure.persistence.RepositoryDatabaseTestSupport;
import com.zeroio.platform.domain.model.tenant.WorkspaceSessionHandoffToken;

class WorkspaceSessionHandoffCommandTest {

  @BeforeEach
  void setUp() throws SQLException {
    RepositoryDatabaseTestSupport.configureInMemoryH2Database();
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE workspace_session_handoff_tokens ("
            + "workspace_session_handoff_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "token VARCHAR(100) NOT NULL,"
            + "user_id BIGINT NOT NULL,"
            + "workspace_id BIGINT NOT NULL,"
            + "resource VARCHAR(512) NOT NULL,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "consumed_at TIMESTAMP"
            + ")");
  }

  @AfterEach
  void tearDown() {
    RepositoryDatabaseTestSupport.shutdown();
  }

  @Test
  void issueThenConsumeToken_roundTripSucceeds() {
    String token = WorkspaceSessionHandoffCommand.issueToken(42L, 7L, "/dashboard");
    assertNotNull(token);

    WorkspaceSessionHandoffToken consumed = WorkspaceSessionHandoffCommand.consumeToken(token);
    assertNotNull(consumed);
    assertEquals(42L, consumed.getMainTenantUserId());
    assertEquals(7L, consumed.getWorkspaceId());
    assertEquals("/dashboard", consumed.getResource());
  }

  @Test
  void consumeToken_isSingleUse() {
    String token = WorkspaceSessionHandoffCommand.issueToken(42L, 7L, "/");

    assertNotNull(WorkspaceSessionHandoffCommand.consumeToken(token));
    assertNull(WorkspaceSessionHandoffCommand.consumeToken(token));
  }

  @Test
  void consumeToken_returnsNullForUnknownToken() {
    assertNull(WorkspaceSessionHandoffCommand.consumeToken("unknown-token"));
  }

  @Test
  void issueToken_requiresUserIdWorkspaceIdAndLoginToken() {
    assertNull(WorkspaceSessionHandoffCommand.issueToken(0L, 7L, "/"));
    assertNull(WorkspaceSessionHandoffCommand.issueToken(42L, 0L, "/"));
  }
}
