/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.simisinc.platform.infrastructure.persistence;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.github.rajkowski.database.DataConstraints;
import com.simisinc.platform.domain.model.App;
import com.simisinc.platform.domain.model.BlockedIP;
import com.simisinc.platform.domain.model.DatabaseVersion;
import com.simisinc.platform.domain.model.Group;
import com.simisinc.platform.domain.model.Role;
import com.simisinc.platform.domain.model.Session;
import com.simisinc.platform.domain.model.SiteProperty;
import com.simisinc.platform.domain.model.User;
import com.simisinc.platform.domain.model.UserProfile;
import com.simisinc.platform.domain.model.Visitor;
import com.simisinc.platform.infrastructure.persistence.admin.PermissionGroupRepository;

class RootPersistenceRepositoryTest {

    @BeforeEach
    void setUp() throws SQLException {
        RepositoryDatabaseTestSupport.configureInMemoryH2Database();
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE groups ("
                        + "group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "name VARCHAR(255),"
                        + "unique_id VARCHAR(255),"
                        + "description TEXT,"
                        + "oauth_path VARCHAR(255),"
                        + "user_count INTEGER DEFAULT 0"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE lookup_role ("
                        + "role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "level INTEGER DEFAULT 0,"
                        + "code VARCHAR(255),"
                        + "title VARCHAR(255),"
                        + "oauth_path VARCHAR(255)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE apps ("
                        + "app_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "name VARCHAR(255),"
                        + "summary TEXT,"
                        + "public_key VARCHAR(255),"
                        + "private_key VARCHAR(255),"
                        + "created_by BIGINT DEFAULT -1,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "enabled BOOLEAN DEFAULT TRUE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE block_list ("
                        + "block_list_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "ip_address VARCHAR(255),"
                        + "reason TEXT,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE database_version ("
                        + "version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "file VARCHAR(255),"
                        + "version VARCHAR(255),"
                        + "installed TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE site_properties ("
                        + "property_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "property_order INTEGER DEFAULT 100,"
                        + "property_label VARCHAR(255),"
                        + "property_name VARCHAR(255),"
                        + "property_value VARCHAR(255),"
                        + "property_type VARCHAR(255)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE sessions ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "session_id VARCHAR(255),"
                        + "source VARCHAR(255),"
                        + "ip_address VARCHAR(255),"
                        + "user_agent VARCHAR(255),"
                        + "referer VARCHAR(255),"
                        + "continent VARCHAR(255),"
                        + "country_iso VARCHAR(255),"
                        + "country VARCHAR(255),"
                        + "city VARCHAR(255),"
                        + "state_iso VARCHAR(255),"
                        + "state VARCHAR(255),"
                        + "postal_code VARCHAR(255),"
                        + "timezone VARCHAR(255),"
                        + "is_bot BOOLEAN DEFAULT FALSE,"
                        + "latitude DOUBLE,"
                        + "longitude DOUBLE,"
                        + "metro_code INTEGER,"
                        + "app_id BIGINT,"
                        + "visitor_id BIGINT,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE visitors ("
                        + "visitor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "token VARCHAR(255),"
                        + "session_id VARCHAR(255),"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE users ("
                        + "user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "unique_id VARCHAR(255),"
                        + "first_name VARCHAR(255),"
                        + "last_name VARCHAR(255),"
                        + "organization VARCHAR(255),"
                        + "nickname VARCHAR(255),"
                        + "email VARCHAR(255),"
                        + "username VARCHAR(255),"
                        + "title VARCHAR(255),"
                        + "department VARCHAR(255),"
                        + "timezone VARCHAR(255),"
                        + "city VARCHAR(255),"
                        + "state VARCHAR(255),"
                        + "country VARCHAR(255),"
                        + "postal_code VARCHAR(255),"
                        + "password VARCHAR(255),"
                        + "enabled BOOLEAN DEFAULT TRUE,"
                        + "account_token VARCHAR(255),"
                        + "validated TIMESTAMP,"
                        + "created_by BIGINT DEFAULT -1,"
                        + "modified_by BIGINT DEFAULT -1,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "latitude DOUBLE DEFAULT 0,"
                        + "longitude DOUBLE DEFAULT 0,"
                        + "description TEXT,"
                        + "description_text TEXT,"
                        + "image_url VARCHAR(255),"
                        + "video_url VARCHAR(255),"
                        + "field_values VARCHAR(2048)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE user_groups ("
                        + "user_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "user_id BIGINT,"
                        + "group_id BIGINT,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE user_roles ("
                        + "user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "user_id BIGINT,"
                        + "role_id BIGINT,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE permission_policies ("
                        + "policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "group_code VARCHAR(255),"
                        + "group_name VARCHAR(255),"
                        + "policy_text TEXT,"
                        + "enabled BOOLEAN DEFAULT TRUE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE permission_group_members ("
                        + "group_code VARCHAR(255),"
                        + "action_name VARCHAR(255),"
                        + "member_type VARCHAR(255)"
                        + ")");

        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO groups (name, unique_id, description, oauth_path, user_count) VALUES ('Admins', 'admins', 'Admin group', '/oauth/admins', 0)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO lookup_role (level, code, title, oauth_path) VALUES (10, 'admin', 'Administrator', '/oauth/admin')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO apps (name, summary, public_key, private_key, created_by) VALUES ('Test App', 'Summary', 'public-key-1', 'private-key-1', 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO block_list (ip_address, reason) VALUES ('127.0.0.1', 'Local test block')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO database_version (file, version) VALUES ('db/001_init.sql', '1.0.0')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO site_properties (property_order, property_label, property_name, property_value, property_type) VALUES (5, 'Site name', 'site.name', 'Test Site', 'text')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO users (unique_id, first_name, last_name, email, username, password, enabled, created_by, modified_by, field_values) "
                        + "VALUES ('u1', 'Test', 'User', 'test@example.com', 'tester', 'pw', TRUE, 1, 1, '[{\"name\":\"favorite_color\",\"label\":\"Favorite Color\",\"value\":\"Blue\"}]')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO permission_policies (group_code, group_name, policy_text, enabled) VALUES ('admins', 'Admins', 'allow admin', TRUE)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO permission_group_members (group_code, action_name, member_type) VALUES ('admins', 'edit', 'role')");
    }

    @AfterEach
    void tearDown() {
        RepositoryDatabaseTestSupport.shutdown();
    }

    @Test
    void appRepository_addAndFindByPublicKey() {
        App app = new App();
        app.setName("SDK App");
        app.setSummary("SDK summary");
        app.setPublicKey("public-key-2");
        app.setPrivateKey("private-key-2");
        app.setCreatedBy(1L);

        App saved = AppRepository.save(app);
        assertNotNull(saved);
        assertTrue(saved.getId() > 0);

        App found = AppRepository.findByPublicKey("public-key-2");
        assertNotNull(found);
        assertEquals("SDK App", found.getName());
        assertEquals("private-key-2", found.getPrivateKey());
    }

    @Test
    void blockedIPRepository_addAndFindByIpAddress() {
        BlockedIP blockedIP = new BlockedIP();
        blockedIP.setIpAddress("10.0.0.1");
        blockedIP.setReason("Known abuse");

        BlockedIP saved = BlockedIPRepository.add(blockedIP);
        assertNotNull(saved);
        assertTrue(saved.getId() > 0);

        BlockedIP found = BlockedIPRepository.findByIpAddress("10.0.0.1");
        assertNotNull(found);
        assertEquals("Known abuse", found.getReason());
        assertEquals(2, BlockedIPRepository.findAll(new DataConstraints()).size());
    }

    @Test
    void databaseVersionRepository_saveAndFindByVersion() {
        DatabaseVersion version = new DatabaseVersion();
        version.setFile("db/002_feature.sql");
        version.setVersion("2.0.0");

        DatabaseVersion saved = DatabaseVersionRepository.save(version);
        assertNotNull(saved);
        assertTrue(saved.getId() > 0);

        DatabaseVersion found = DatabaseVersionRepository.findByVersion("2.0.0");
        assertNotNull(found);
        assertEquals("db/002_feature.sql", found.getFile());
        assertEquals(2, DatabaseVersionRepository.findAll().size());
        assertEquals(2, DatabaseVersionRepository.count());
    }

    @Test
    void groupRepository_findAndUpdateUserCount() {
        Group group = GroupRepository.findByUniqueId("admins");
        assertNotNull(group);
        assertEquals("Admins", group.getName());

        Group byName = GroupRepository.findByName("admins");
        assertNotNull(byName);
        assertEquals("admins", byName.getUniqueId());

        GroupRepository.updateUserCount(group.getId(), 3);
        Group updated = GroupRepository.findById(group.getId());
        assertNotNull(updated);
        assertEquals(3, updated.getUserCount());
    }

    @Test
    void roleRepository_findByCode() {
        Role role = RoleRepository.findByCode("admin");
        assertNotNull(role);
        assertEquals("Administrator", role.getTitle());
        assertEquals("/oauth/admin", role.getOAuthPath());

        Role byId = RoleRepository.findById((int) role.getId());
        assertNotNull(byId);
        assertEquals("admin", byId.getCode());
    }

    @Test
    void sitePropertyRepository_saveAndFindAllByPrefix() {
        List<SiteProperty> list = SitePropertyRepository.findAllByPrefix("site");
        assertNotNull(list);
        assertFalse(list.isEmpty());

        SiteProperty existing = list.get(0);
        existing.setValue("Updated Site");
        SiteProperty saved = SitePropertyRepository.save(existing);
        assertNotNull(saved);
        assertEquals("Updated Site", SitePropertyRepository.findAll().get(0).getValue());
    }

    @Test
    void sessionRepository_addAndCountSessions() throws SQLException {
        Session session = new Session();
        session.setSessionId("sess-123");
        session.setSource("web");
        session.setIpAddress("127.0.0.1");
        session.setUserAgent("Mozilla/5.0");
        session.setReferer("https://example.com");
        session.setCountry("United States");
        session.setCity("Austin");
        session.setState("TX");
        session.setLatitude(30.2672);
        session.setLongitude(-97.7431);
        session.setIsBot(false);

        Session saved = SessionRepository.add(session);
        assertNotNull(saved);
        assertTrue(saved.getId() > 0);

        List<Session> sessions = SessionRepository.findAll();
        assertNotNull(sessions);
        assertFalse(sessions.isEmpty());
        assertEquals("sess-123", sessions.get(0).getSessionId());

        Timestamp start = new Timestamp(System.currentTimeMillis() - 60000);
        Timestamp end = new Timestamp(System.currentTimeMillis() + 60000);
        assertEquals(1, SessionRepository.countDistinctSessions(start, end));
    }

    @Test
    void userRepository_addAndFindByUsernameAndRoles() {
        User user = new User();
        user.setUniqueId("u2");
        user.setFirstName("Second");
        user.setLastName("User");
        user.setEmail("second@example.com");
        user.setUsername("seconduser");
        user.setPassword("pw");
        user.setEnabled(true);
        user.setCreatedBy(1L);

        Group group = new Group();
        group.setId(1L);
        GroupRepository.updateUserCount(1L, 0);

        Role role = new Role();
        role.setId(1);
        user.setGroupList(List.of(group));
        user.setRoleList(List.of(role));

        User saved = UserRepository.save(user);
        assertNotNull(saved);
        assertTrue(saved.getId() > 0);

        User found = UserRepository.findByUsername("seconduser");
        assertNotNull(found);
        assertEquals("second@example.com", found.getEmail());
        assertTrue(UserRepository.findAll(new UserSpecification(), new DataConstraints()).size() >= 2);
    }

    @Test
    void userProfileRepository_findByUserId_andFieldValues() {
        UserProfile profile = UserProfileRepository.findByUserId(1L);
        assertNotNull(profile);
        assertEquals("Test", profile.getFirstName());
        assertEquals("User", profile.getLastName());
    }

    @Test
    void visitorRepository_addAndFindByToken() {
        Session session = new Session();
        session.setSessionId("visitor-session");
        session.setSource("web");
        session.setIpAddress("127.0.0.2");
        SessionRepository.add(session);

        Visitor visitor = new Visitor();
        visitor.setToken("token-abc");
        visitor.setSessionId("visitor-session");

        Visitor saved = VisitorRepository.add(visitor);
        assertNotNull(saved);
        assertTrue(saved.getId() > 0);

        Visitor found = VisitorRepository.findByToken("token-abc");
        assertNotNull(found);
        assertEquals("visitor-session", found.getSessionId());
    }

    @Test
    void permissionGroupRepository_findPoliciesAndMembers() {
        List<com.simisinc.platform.domain.model.admin.PermissionGroup> policies = PermissionGroupRepository.findAllPolicies();
        assertNotNull(policies);
        assertEquals(1, policies.size());
        assertEquals("admins", policies.get(0).getCode());

        Map<String, List<String[]>> members = PermissionGroupRepository.findAllMembers();
        assertNotNull(members);
        assertTrue(members.containsKey("admins"));
        assertEquals("edit", members.get("admins").get(0)[0]);
    }
}
