/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.simisinc.platform.infrastructure.persistence.cms;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.SQLException;
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.github.rajkowski.database.DataConstraints;
import com.simisinc.platform.domain.model.cms.Blog;
import com.simisinc.platform.infrastructure.persistence.RepositoryDatabaseTestSupport;

class BlogRepositoryTest {

  @BeforeEach
  void setUp() throws SQLException {
    RepositoryDatabaseTestSupport.configureInMemoryH2Database();
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE users (user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(255) NOT NULL)");
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE blogs ("
            + "blog_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "blog_unique_id VARCHAR(255) UNIQUE NOT NULL,"
            + "name VARCHAR(255) NOT NULL,"
            + "description TEXT,"
            + "created_by BIGINT NOT NULL,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "modified_by BIGINT NOT NULL,"
            + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "enabled BOOLEAN DEFAULT TRUE"
            + ")");
  }

  @AfterEach
  void tearDown() {
    RepositoryDatabaseTestSupport.shutdown();
  }

  @Test
  void addAndFindByUniqueId() {
    Blog blog = new Blog();
    blog.setUniqueId("news-2026");
    blog.setName("Latest News");
    blog.setDescription("A breaking update");
    blog.setCreatedBy(1L);
    blog.setModifiedBy(1L);
    blog.setEnabled(true);

    Blog saved = BlogRepository.add(blog);

    assertNotNull(saved);
    assertTrue(saved.getId() > 0);

    Blog found = BlogRepository.findByUniqueId("news-2026");
    assertNotNull(found);
    assertEquals("Latest News", found.getName());
    assertEquals("A breaking update", found.getDescription());
    assertTrue(found.getEnabled());
  }

  @Test
  void updateAndFindAll() {
    Blog first = new Blog();
    first.setUniqueId("news-1");
    first.setName("First Story");
    first.setCreatedBy(1L);
    first.setModifiedBy(1L);
    first.setEnabled(false);
    BlogRepository.add(first);

    Blog second = new Blog();
    second.setUniqueId("news-2");
    second.setName("Second Story");
    second.setCreatedBy(1L);
    second.setModifiedBy(1L);
    second.setEnabled(true);
    BlogRepository.add(second);

    List<Blog> allBlogs = BlogRepository.findAll(new BlogSpecification(), new DataConstraints());
    assertEquals(2, allBlogs.size());

    first.setName("Updated Story");
    first.setEnabled(true);
    Blog updated = BlogRepository.save(first);
    assertNotNull(updated);

    Blog loaded = BlogRepository.findById(first.getId());
    assertNotNull(loaded);
    assertEquals("Updated Story", loaded.getName());
    assertTrue(loaded.getEnabled());
  }
}
