/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.simisinc.platform.infrastructure.persistence.cms;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.sql.SQLException;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.simisinc.platform.domain.model.cms.Blog;
import com.simisinc.platform.domain.model.cms.BlogPost;
import com.simisinc.platform.domain.model.cms.Calendar;
import com.simisinc.platform.domain.model.cms.CalendarEvent;
import com.simisinc.platform.domain.model.cms.Content;
import com.simisinc.platform.domain.model.cms.FileItem;
import com.simisinc.platform.domain.model.cms.FileVersion;
import com.simisinc.platform.domain.model.cms.Folder;
import com.simisinc.platform.domain.model.cms.GitPublishSettings;
import com.simisinc.platform.domain.model.cms.Image;
import com.simisinc.platform.domain.model.cms.ImageVersion;
import com.simisinc.platform.domain.model.cms.MenuItem;
import com.simisinc.platform.domain.model.cms.MenuTab;
import com.simisinc.platform.domain.model.cms.Theme;
import com.simisinc.platform.domain.model.cms.WebContainer;
import com.simisinc.platform.domain.model.cms.WebPage;
import com.simisinc.platform.domain.model.cms.WebPageHit;
import com.simisinc.platform.domain.model.cms.WebPageTemplate;
import com.simisinc.platform.domain.model.cms.WebSearch;
import com.simisinc.platform.domain.model.cms.Wiki;
import com.simisinc.platform.infrastructure.persistence.RepositoryDatabaseTestSupport;

class CmsPersistenceRepositoryTest {

    @BeforeEach
    void setUp() throws SQLException {
        RepositoryDatabaseTestSupport.configureInMemoryH2Database();
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE blogs ("
                        + "blog_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "blog_unique_id VARCHAR(255) UNIQUE NOT NULL,"
                        + "name VARCHAR(255) NOT NULL,"
                        + "description TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "enabled BOOLEAN DEFAULT TRUE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE blog_posts ("
                        + "post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "blog_id BIGINT NOT NULL,"
                        + "post_unique_id VARCHAR(255) NOT NULL,"
                        + "title VARCHAR(255),"
                        + "body TEXT,"
                        + "body_text TEXT,"
                        + "summary TEXT,"
                        + "keywords VARCHAR(255),"
                        + "image_url VARCHAR(255),"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "published TIMESTAMP,"
                        + "archived TIMESTAMP,"
                        + "start_date TIMESTAMP,"
                        + "end_date TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE calendars ("
                        + "calendar_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "calendar_unique_id VARCHAR(255) UNIQUE NOT NULL,"
                        + "name VARCHAR(255) NOT NULL,"
                        + "description TEXT,"
                        + "color VARCHAR(32),"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "enabled BOOLEAN DEFAULT TRUE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE calendar_events ("
                        + "event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "calendar_id BIGINT NOT NULL,"
                        + "event_unique_id VARCHAR(255) NOT NULL,"
                        + "title VARCHAR(255),"
                        + "body TEXT,"
                        + "summary TEXT,"
                        + "all_day BOOLEAN DEFAULT FALSE,"
                        + "start_date TIMESTAMP,"
                        + "end_date TIMESTAMP,"
                        + "details_url VARCHAR(255),"
                        + "sign_up_url VARCHAR(255),"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "published TIMESTAMP,"
                        + "archived TIMESTAMP,"
                        + "latitude DOUBLE DEFAULT 0,"
                        + "longitude DOUBLE DEFAULT 0,"
                        + "location_name VARCHAR(255),"
                        + "street VARCHAR(255),"
                        + "address_line_2 VARCHAR(255),"
                        + "address_line_3 VARCHAR(255),"
                        + "city VARCHAR(255),"
                        + "state VARCHAR(255),"
                        + "country VARCHAR(255),"
                        + "postal_code VARCHAR(255),"
                        + "county VARCHAR(255),"
                        + "image_url VARCHAR(255),"
                        + "video_url VARCHAR(255),"
                        + "video_embed TEXT,"
                        + "script_embed TEXT"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE content ("
                        + "content_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "content_unique_id VARCHAR(255) UNIQUE NOT NULL,"
                        + "content TEXT,"
                        + "content_text TEXT,"
                        + "draft_content TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "enabled BOOLEAN DEFAULT TRUE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE folders ("
                        + "folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "folder_unique_id VARCHAR(255),"
                        + "name VARCHAR(255) NOT NULL,"
                        + "summary TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "file_count INTEGER DEFAULT 0,"
                        + "privacy_types VARCHAR(255),"
                        + "has_allowed_groups BOOLEAN DEFAULT FALSE,"
                        + "guest_privacy_type INTEGER DEFAULT 0,"
                        + "allows_guests BOOLEAN DEFAULT FALSE,"
                        + "enabled BOOLEAN DEFAULT TRUE,"
                        + "has_categories BOOLEAN DEFAULT FALSE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE folder_groups ("
                        + "allowed_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "folder_id BIGINT NOT NULL,"
                        + "group_id BIGINT NOT NULL,"
                        + "privacy_type INTEGER DEFAULT 0,"
                        + "view_all BOOLEAN DEFAULT TRUE,"
                        + "add_permission BOOLEAN DEFAULT FALSE,"
                        + "edit_permission BOOLEAN DEFAULT FALSE,"
                        + "delete_permission BOOLEAN DEFAULT FALSE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE folder_categories ("
                        + "category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "folder_id BIGINT NOT NULL,"
                        + "name VARCHAR(255) NOT NULL,"
                        + "summary TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "enabled BOOLEAN DEFAULT TRUE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE menu_tabs ("
                        + "menu_tab_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "tab_order INTEGER DEFAULT 0,"
                        + "name VARCHAR(255),"
                        + "link VARCHAR(255),"
                        + "icon VARCHAR(255),"
                        + "page_title VARCHAR(255),"
                        + "page_keywords VARCHAR(255),"
                        + "page_description TEXT,"
                        + "draft BOOLEAN DEFAULT FALSE,"
                        + "enabled BOOLEAN DEFAULT TRUE,"
                        + "comments TEXT"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE menu_items ("
                        + "menu_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "menu_tab_id BIGINT NOT NULL,"
                        + "item_order INTEGER DEFAULT 0,"
                        + "name VARCHAR(255),"
                        + "link VARCHAR(255),"
                        + "page_title VARCHAR(255),"
                        + "page_keywords VARCHAR(255),"
                        + "page_description TEXT,"
                        + "draft BOOLEAN DEFAULT FALSE,"
                        + "enabled BOOLEAN DEFAULT TRUE,"
                        + "comments TEXT"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE themes ("
                        + "theme_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "name VARCHAR(255) UNIQUE NOT NULL,"
                        + "entries TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE web_containers ("
                        + "container_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "container_name VARCHAR(255) UNIQUE NOT NULL,"
                        + "label VARCHAR(255),"
                        + "image_path VARCHAR(255),"
                        + "draft BOOLEAN DEFAULT FALSE,"
                        + "container_xml TEXT,"
                        + "draft_xml TEXT"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE web_searches ("
                        + "search_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "page_path VARCHAR(255),"
                        + "query VARCHAR(255),"
                        + "ip_address VARCHAR(255),"
                        + "session_id VARCHAR(255),"
                        + "is_logged_in BOOLEAN DEFAULT FALSE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE web_pages ("
                        + "web_page_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "link VARCHAR(255) NOT NULL,"
                        + "redirect_url VARCHAR(255),"
                        + "page_title VARCHAR(255),"
                        + "page_keywords VARCHAR(255),"
                        + "page_description TEXT,"
                        + "draft BOOLEAN DEFAULT FALSE,"
                        + "enabled BOOLEAN DEFAULT FALSE,"
                        + "searchable BOOLEAN DEFAULT FALSE,"
                        + "show_in_sitemap BOOLEAN DEFAULT FALSE,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "role_id_list VARCHAR(255),"
                        + "page_xml TEXT,"
                        + "draft_page_xml TEXT,"
                        + "comments TEXT,"
                        + "page_image_url VARCHAR(255),"
                        + "has_redirect BOOLEAN DEFAULT FALSE,"
                        + "sitemap_priority DECIMAL(10, 3),"
                        + "sitemap_changefreq VARCHAR(50),"
                        + "tags VARCHAR(2048),"
                        + "page_text TEXT,"
                        + "tsv OTHER"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE web_page_templates ("
                        + "template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "name VARCHAR(255) UNIQUE NOT NULL,"
                        + "image_path VARCHAR(255),"
                        + "page_xml TEXT,"
                        + "template_order INTEGER DEFAULT 10,"
                        + "description TEXT,"
                        + "css TEXT,"
                        + "category VARCHAR(255)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE web_page_hierarchy ("
                        + "hierarchy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "web_page_id BIGINT NOT NULL,"
                        + "parent_page_id BIGINT,"
                        + "sort_order INTEGER DEFAULT 0,"
                        + "depth INTEGER DEFAULT 0,"
                        + "path VARCHAR(255),"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE wikis ("
                        + "wiki_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "wiki_unique_id VARCHAR(255) UNIQUE NOT NULL,"
                        + "name VARCHAR(255) NOT NULL,"
                        + "description TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "enabled BOOLEAN DEFAULT TRUE,"
                        + "starting_page BIGINT DEFAULT -1"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE wiki_pages ("
                        + "wiki_page_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "wiki_id BIGINT NOT NULL,"
                        + "page_unique_id VARCHAR(255) NOT NULL,"
                        + "title VARCHAR(255),"
                        + "body TEXT,"
                        + "body_text TEXT,"
                        + "summary TEXT,"
                        + "keywords VARCHAR(255),"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "published TIMESTAMP,"
                        + "archived TIMESTAMP,"
                        + "start_date TIMESTAMP,"
                        + "end_date TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE git_publish_settings ("
                        + "settings_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "enabled BOOLEAN DEFAULT FALSE,"
                        + "git_provider VARCHAR(255),"
                        + "repository_url VARCHAR(255),"
                        + "branch_name VARCHAR(255),"
                        + "base_branch VARCHAR(255),"
                        + "access_token VARCHAR(255),"
                        + "username VARCHAR(255),"
                        + "email VARCHAR(255),"
                        + "commit_message_template TEXT,"
                        + "auto_create_pr BOOLEAN DEFAULT FALSE,"
                        + "pr_title_template VARCHAR(255),"
                        + "pr_description_template TEXT,"
                        + "target_directory VARCHAR(255),"
                        + "created_by BIGINT,"
                        + "modified_by BIGINT,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE stylesheets ("
                        + "stylesheet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "web_page_id BIGINT,"
                        + "css TEXT,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE images ("
                        + "image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "folder_id BIGINT NOT NULL,"
                        + "filename VARCHAR(255),"
                        + "title VARCHAR(255),"
                        + "alt_text VARCHAR(255),"
                        + "description TEXT,"
                        + "version VARCHAR(64),"
                        + "version_number INTEGER DEFAULT 1,"
                        + "extension VARCHAR(32),"
                        + "path VARCHAR(255),"
                        + "file_length BIGINT,"
                        + "file_type VARCHAR(255),"
                        + "mime_type VARCHAR(255),"
                        + "file_hash VARCHAR(255),"
                        + "web_path VARCHAR(255),"
                        + "width INTEGER,"
                        + "height INTEGER,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "processed TIMESTAMP,"
                        + "processed_path VARCHAR(255),"
                        + "processed_file_length BIGINT,"
                        + "processed_file_type VARCHAR(255),"
                        + "processed_width INTEGER,"
                        + "processed_height INTEGER"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE image_versions ("
                        + "version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "image_id BIGINT NOT NULL,"
                        + "version_number INTEGER DEFAULT 1,"
                        + "filename VARCHAR(255),"
                        + "path VARCHAR(255),"
                        + "file_length BIGINT,"
                        + "file_type VARCHAR(50),"
                        + "width INTEGER,"
                        + "height INTEGER,"
                        + "is_current BOOLEAN DEFAULT FALSE,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "notes TEXT"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE files ("
                        + "file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "folder_id BIGINT NOT NULL,"
                        + "sub_folder_id BIGINT,"
                        + "category_id BIGINT,"
                        + "filename VARCHAR(255),"
                        + "title VARCHAR(255),"
                        + "barcode VARCHAR(255),"
                        + "version VARCHAR(100),"
                        + "extension VARCHAR(50),"
                        + "path VARCHAR(255),"
                        + "file_length BIGINT,"
                        + "file_type VARCHAR(50),"
                        + "mime_type VARCHAR(100),"
                        + "file_hash VARCHAR(255),"
                        + "width INTEGER,"
                        + "height INTEGER,"
                        + "summary TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "processed TIMESTAMP,"
                        + "expiration_date TIMESTAMP,"
                        + "privacy_type INTEGER,"
                        + "default_token VARCHAR(255),"
                        + "version_count INTEGER DEFAULT 0,"
                        + "download_count BIGINT DEFAULT 0,"
                        + "web_path VARCHAR(255),"
                        + "tags VARCHAR(2048),"
                        + "document_text TEXT"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE file_versions ("
                        + "version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "file_id BIGINT NOT NULL,"
                        + "folder_id BIGINT NOT NULL,"
                        + "sub_folder_id BIGINT,"
                        + "category_id BIGINT,"
                        + "filename VARCHAR(255),"
                        + "title VARCHAR(255),"
                        + "version VARCHAR(100),"
                        + "extension VARCHAR(50),"
                        + "path VARCHAR(255),"
                        + "file_length BIGINT,"
                        + "file_type VARCHAR(50),"
                        + "mime_type VARCHAR(100),"
                        + "file_hash VARCHAR(255),"
                        + "width INTEGER,"
                        + "height INTEGER,"
                        + "summary TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "download_count BIGINT DEFAULT 0,"
                        + "web_path VARCHAR(255)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE form_data ("
                        + "form_data_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "form_unique_id VARCHAR(255),"
                        + "ip_address VARCHAR(255),"
                        + "session_id VARCHAR(255),"
                        + "url VARCHAR(255),"
                        + "flagged_as_spam BOOLEAN DEFAULT FALSE,"
                        + "created_by BIGINT,"
                        + "modified_by BIGINT,"
                        + "query_params TEXT,"
                        + "field_values TEXT,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "claimed TIMESTAMP,"
                        + "claimed_by BIGINT,"
                        + "dismissed TIMESTAMP,"
                        + "dismissed_by BIGINT,"
                        + "processed TIMESTAMP,"
                        + "processed_by BIGINT,"
                        + "processed_system VARCHAR(255)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE web_page_hits ("
                        + "hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "method VARCHAR(32),"
                        + "page_path VARCHAR(255),"
                        + "web_page_id BIGINT NOT NULL,"
                        + "ip_address VARCHAR(255),"
                        + "session_id VARCHAR(255),"
                        + "is_logged_in BOOLEAN DEFAULT FALSE,"
                        + "hit_date TIMESTAMP,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE table_of_contents ("
                        + "toc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "toc_unique_id VARCHAR(255) UNIQUE NOT NULL,"
                        + "name VARCHAR(255),"
                        + "created_by BIGINT,"
                        + "modified_by BIGINT,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "entries TEXT"
                        + ")");
    }

    @AfterEach
    void tearDown() {
        RepositoryDatabaseTestSupport.shutdown();
    }

    @Test
    void blogAndBlogPostRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO blogs (blog_unique_id, name, description, created_by, modified_by, enabled) VALUES ('news', 'News', 'Daily updates', 1, 1, true)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO blog_posts (blog_id, post_unique_id, title, body, body_text, summary, created_by, modified_by, published, archived) VALUES (1, 'intro', 'Welcome', 'Hello world', 'Hello world', 'Short intro', 1, 1, CURRENT_TIMESTAMP, NULL)");

        Blog blog = BlogRepository.findByUniqueId("news");
        assertNotNull(blog);
        assertEquals("News", blog.getName());

        BlogPost post = BlogPostRepository.findByUniqueId(1L, "intro");
        assertNotNull(post);
        assertEquals("Welcome", post.getTitle());
        assertEquals(1L, post.getBlogId());
    }

    @Test
    void calendarAndContentRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO calendars (calendar_unique_id, name, description, color, created_by, modified_by, enabled) VALUES ('holidays', 'Holidays', 'Seasonal events', '#ff0000', 1, 1, true)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO calendar_events (calendar_id, event_unique_id, title, summary, created_by, modified_by, start_date, end_date) VALUES (1, 'event-1', 'Launch Day', 'Launch event', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO content (content_unique_id, content, content_text, created_by, modified_by, enabled) VALUES ('home', '<p>Welcome</p>', 'Welcome', 1, 1, true)");

        Calendar calendar = CalendarRepository.findByUniqueId("holidays");
        assertNotNull(calendar);
        assertEquals("Holidays", calendar.getName());

        CalendarEvent event = CalendarEventRepository.findByUniqueId(1L, "event-1");
        assertNotNull(event);
        assertEquals("Launch Day", event.getTitle());

        Content content = ContentRepository.findByUniqueId("home");
        assertNotNull(content);
        assertEquals("<p>Welcome</p>", content.getContent());
    }

    @Test
    void folderAndMenuRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO folders (folder_unique_id, name, summary, created_by, modified_by, allows_guests, guest_privacy_type, has_allowed_groups, has_categories) VALUES ('docs', 'Documents', 'Docs', 1, 1, true, 0, false, false)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO folder_groups (folder_id, group_id, privacy_type, view_all, add_permission, edit_permission, delete_permission) VALUES (1, 10, 0, true, true, true, false)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO folder_categories (folder_id, name, summary, created_by, modified_by) VALUES (1, 'General', 'General docs', 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO menu_tabs (tab_order, name, link, page_title, enabled) VALUES (1, 'Main', '/main', 'Main', true)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO menu_items (menu_tab_id, item_order, name, link, page_title, enabled) VALUES (1, 1, 'Home', '/', 'Home', true)");

        Folder folder = FolderRepository.findByUniqueId("docs");
        assertNotNull(folder);
        assertEquals("Documents", folder.getName());
        assertEquals(1, FolderGroupRepository.findAllByFolderId(folder.getId()).size());
        assertEquals(1, FolderCategoryRepository.findAllByFolderId(folder.getId()).size());

        MenuTab menuTab = MenuTabRepository.findByLink("/main");
        assertNotNull(menuTab);
        assertEquals("Main", menuTab.getName());

        MenuItem menuItem = MenuItemRepository.findByLink("/");
        assertNotNull(menuItem);
        assertEquals("Home", menuItem.getName());
    }

    @Test
    void themeAndWebRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO themes (name, created_by, modified_by) VALUES ('default', 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO web_containers (container_name, label, image_path, draft, container_xml, draft_xml) VALUES ('header.default', 'Header', '/header.png', false, '<header />', '<header />')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO web_searches (page_path, query, ip_address, session_id, is_logged_in) VALUES ('/about', 'hello', '127.0.0.1', 's-1', true)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO web_pages (link, page_title, page_description, draft, enabled, searchable, show_in_sitemap, created_by, modified_by, page_xml) VALUES ('/about', 'About', 'About us', false, true, true, true, 1, 1, '<page>About</page>')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO web_page_templates (name, image_path, page_xml, template_order, description, css, category) VALUES ('default', '/img/default.png', '<template />', 10, 'Default', 'body {}', 'layout')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO web_page_hierarchy (web_page_id, parent_page_id, sort_order, depth, path, created, modified) VALUES (1, -1, 1, 0, '/1/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO wikis (wiki_unique_id, name, description, created_by, modified_by, enabled) VALUES ('help', 'Help', 'Help wiki', 1, 1, true)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO wiki_pages (wiki_id, page_unique_id, title, body, body_text, summary, created_by, modified_by, published) VALUES (1, 'home', 'Home', 'Wiki body', 'Wiki body', 'Summary', 1, 1, CURRENT_TIMESTAMP)");

        Theme theme = ThemeRepository.findByName("default");
        assertNotNull(theme);
        assertEquals("default", theme.getName());

        WebContainer container = WebContainerRepository.findByName("header.default");
        assertNotNull(container);
        assertEquals("Header", container.getLabel());

        WebSearch search = WebSearchRepository.save(new com.simisinc.platform.domain.model.cms.WebSearch());
        assertNotNull(search);

        WebPage page = WebPageRepository.findByLink("/about");
        assertNotNull(page);
        assertEquals("About", page.getTitle());

        WebPageTemplate template = WebPageTemplateRepository.findByName("default");
        assertNotNull(template);
        assertEquals("default", template.getName());

        assertNotNull(WebPageHierarchyRepository.findByPageId(1L));

        Wiki wiki = WikiRepository.findByUniqueId("help");
        assertNotNull(wiki);
        assertEquals("Help", wiki.getName());
        assertEquals("Home", WikiPageRepository.findByUniqueId(1L, "home").getTitle());
    }

    @Test
    void settingsAndFilesRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO git_publish_settings (enabled, git_provider, repository_url, branch_name, base_branch, access_token, username, email, commit_message_template, auto_create_pr, pr_title_template, pr_description_template, target_directory, created_by, modified_by) VALUES (true, 'github', 'https://example.com/repo.git', 'main', 'main', 'tok', 'user', 'user@example.com', 'msg', true, 'pr', 'desc', '/tmp', 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO stylesheets (web_page_id, css, modified) VALUES (1, 'body { color: red; }', CURRENT_TIMESTAMP)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO images (folder_id, filename, title, version, extension, path, file_length, mime_type, file_hash, web_path, created_by, modified_by) VALUES (1, 'logo.png', 'Logo', '1', 'png', '/tmp/logo.png', 42, 'image/png', 'hash-1', '/images/logo.png', 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO image_versions (image_id, version_number, filename, path, file_length, file_type, width, height, is_current, created_by, notes) VALUES (1, 1, 'logo.png', '/tmp/logo.png', 42, 'image/png', 100, 80, true, 1, 'Logo version')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO files (folder_id, filename, title, version, extension, path, file_length, file_type, mime_type, web_path, created_by, modified_by) VALUES (1, 'guide.pdf', 'Guide', '1', 'pdf', '/tmp/guide.pdf', 123, 'pdf', 'application/pdf', '/files/guide.pdf', 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO file_versions (file_id, folder_id, filename, title, version, extension, path, file_length, file_type, mime_type, web_path, created_by) VALUES (1, 1, 'guide.pdf', 'Guide', '1', 'pdf', '/tmp/guide.pdf', 123, 'pdf', 'application/pdf', '/files/guide.pdf', 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO form_data (form_unique_id, ip_address, session_id, field_values, created, modified) VALUES ('contact', '127.0.0.1', 'session-1', '{\"name\":\"Ada\"}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO web_page_hits (web_page_id, ip_address, session_id) VALUES (1, '127.0.0.1', 'sess-1')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO table_of_contents (toc_unique_id, name, entries) VALUES ('toc-home', 'Home', NULL)");

        GitPublishSettings settings = GitPublishSettingsRepository.findSettings();
        assertNotNull(settings);
        assertEquals("github", settings.getGitProvider());

        assertNotNull(StylesheetRepository.findByWebPageId(1L));

        Image image = ImageRepository.findByWebPath("/images/logo.png");
        assertNotNull(image);
        assertEquals("Logo", image.getTitle());

        ImageVersion imageVersion = ImageVersionRepository.findById(1L);
        assertNotNull(imageVersion);
        assertEquals("logo.png", imageVersion.getFilename());

        FileItem file = FileItemRepository.findByWebPath("/files/guide.pdf");
        assertNotNull(file);
        assertEquals("Guide", file.getTitle());

        FileVersion fileVersion = FileVersionRepository.findById(1L);
        assertNotNull(fileVersion);
        assertEquals("Guide", fileVersion.getTitle());

        FormDataSpecification formDataSpecification = new FormDataSpecification();
        formDataSpecification.setFormUniqueId("contact");
        assertEquals(1,
                com.simisinc.platform.infrastructure.persistence.cms.FormDataRepository.findAll(formDataSpecification, null).size());

        WebPageHit webPageHit = new WebPageHit();
        webPageHit.setMethod("GET");
        webPageHit.setPagePath("/about");
        webPageHit.setWebPageId(1L);
        webPageHit.setIpAddress("127.0.0.1");
        webPageHit.setSessionId("sess-2");
        webPageHit.setLoggedIn(true);
        assertNotNull(com.simisinc.platform.infrastructure.persistence.cms.WebPageHitRepository.save(webPageHit));

        assertNotNull(TableOfContentsRepository.findByUniqueId("toc-home"));
    }
}
