/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.simisinc.platform.infrastructure.persistence.cms;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.SQLException;
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.github.rajkowski.database.DataConstraints;
import com.simisinc.platform.domain.model.cms.FileItem;
import com.simisinc.platform.domain.model.cms.FileVersion;
import com.simisinc.platform.infrastructure.persistence.RepositoryDatabaseTestSupport;

class FileRepositoryTest {

  @BeforeEach
  void setUp() throws SQLException {
    RepositoryDatabaseTestSupport.configureInMemoryH2Database();
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE folders ("
            + "folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "folder_unique_id VARCHAR(255),"
            + "name VARCHAR(255) NOT NULL,"
            + "summary TEXT,"
            + "created_by BIGINT NOT NULL,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "modified_by BIGINT NOT NULL,"
            + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "file_count INTEGER DEFAULT 0,"
            + "privacy_types VARCHAR(255),"
            + "has_allowed_groups BOOLEAN DEFAULT FALSE,"
            + "guest_privacy_type INTEGER DEFAULT 0,"
            + "allows_guests BOOLEAN DEFAULT FALSE,"
            + "enabled BOOLEAN DEFAULT TRUE,"
            + "has_categories BOOLEAN DEFAULT FALSE"
            + ")");
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE sub_folders ("
            + "sub_folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "folder_id BIGINT NOT NULL,"
            + "name VARCHAR(255),"
            + "summary TEXT,"
            + "created_by BIGINT NOT NULL,"
            + "modified_by BIGINT NOT NULL,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "start_date TIMESTAMP,"
            + "end_date TIMESTAMP,"
            + "file_count INTEGER DEFAULT 0"
            + ")");
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE files ("
            + "file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "folder_id BIGINT NOT NULL,"
            + "sub_folder_id BIGINT,"
            + "category_id BIGINT,"
            + "filename VARCHAR(255) NOT NULL,"
            + "title VARCHAR(255),"
            + "barcode VARCHAR(255),"
            + "version VARCHAR(100),"
            + "extension VARCHAR(50),"
            + "path VARCHAR(255),"
            + "file_length BIGINT,"
            + "file_type VARCHAR(50),"
            + "mime_type VARCHAR(100),"
            + "file_hash VARCHAR(255),"
            + "width INTEGER,"
            + "height INTEGER,"
            + "summary TEXT,"
            + "created_by BIGINT NOT NULL,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "modified_by BIGINT NOT NULL,"
            + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "processed TIMESTAMP,"
            + "expiration_date TIMESTAMP,"
            + "privacy_type INTEGER,"
            + "default_token VARCHAR(255),"
            + "version_count INTEGER DEFAULT 0,"
            + "download_count BIGINT DEFAULT 0,"
            + "web_path VARCHAR(255),"
            + "tags JSONB,"
            + "document_text TEXT"
            + ")");
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE file_versions ("
            + "version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "file_id BIGINT NOT NULL,"
            + "folder_id BIGINT NOT NULL,"
            + "sub_folder_id BIGINT,"
            + "category_id BIGINT,"
            + "filename VARCHAR(255),"
            + "title VARCHAR(255),"
            + "version VARCHAR(100),"
            + "extension VARCHAR(50),"
            + "path VARCHAR(255),"
            + "file_length BIGINT,"
            + "file_type VARCHAR(50),"
            + "mime_type VARCHAR(100),"
            + "file_hash VARCHAR(255),"
            + "width INTEGER,"
            + "height INTEGER,"
            + "summary TEXT,"
            + "created_by BIGINT NOT NULL,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "modified_by BIGINT,"
            + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "download_count BIGINT DEFAULT 0,"
            + "web_path VARCHAR(255)"
            + ")");
    RepositoryDatabaseTestSupport.executeSql(
        "INSERT INTO folders (folder_unique_id, name, summary, created_by, modified_by, file_count, allows_guests, guest_privacy_type, has_allowed_groups, has_categories) "
            + "VALUES ('docs', 'Documents', 'File storage', 1, 1, 0, FALSE, 0, FALSE, FALSE)");
  }

  @AfterEach
  void tearDown() {
    RepositoryDatabaseTestSupport.shutdown();
  }

  @Test
  void addAndFindByWebPath() {
    FileItem file = new FileItem();
    file.setFolderId(1L);
    file.setSubFolderId(-1L);
    file.setCategoryId(-1L);
    file.setFilename("report.pdf");
    file.setTitle("Quarterly Report");
    file.setBarcode("ABC123");
    file.setVersion("1.0");
    file.setExtension("pdf");
    file.setFileServerPath("/tmp/report.pdf");
    file.setFileLength(512L);
    file.setFileType("pdf");
    file.setMimeType("application/pdf");
    file.setFileHash("hash-123");
    file.setWebPath("/files/report.pdf");
    file.setWidth(1200);
    file.setHeight(800);
    file.setSummary("Summary");
    file.setCreatedBy(1L);
    file.setModifiedBy(1L);
    file.setDefaultToken("token-123");
    // file.setTags(new String[] {"quarterly", "finance"});

    FileItem saved = FileItemRepository.save(file);

    assertNotNull(saved);
    assertTrue(saved.getId() > 0);

    FileItem found = FileItemRepository.findByWebPath("/files/report.pdf");
    assertNotNull(found);
    assertEquals("Quarterly Report", found.getTitle());
    assertEquals("pdf", found.getFileType());
    assertEquals("/files/report.pdf", found.getWebPath());

    List<FileVersion> versions = FileVersionRepository.findAll(new FileVersionSpecification(), new DataConstraints());
    assertEquals(1, versions.size());
    assertEquals("Quarterly Report", versions.get(0).getTitle());
  }

  @Test
  void updateAndFindAll() {
    FileItem file = new FileItem();
    file.setFolderId(1L);
    file.setFilename("notes.txt");
    file.setTitle("Notes");
    file.setVersion("1");
    file.setExtension("txt");
    file.setFileServerPath("/tmp/notes.txt");
    file.setFileLength(100L);
    file.setFileType("txt");
    file.setMimeType("text/plain");
    file.setCreatedBy(1L);
    file.setModifiedBy(1L);
    file.setWebPath("/files/notes.txt");
    FileItemRepository.save(file);

    FileItem secondFile = new FileItem();
    secondFile.setFolderId(1L);
    secondFile.setFilename("manual.pdf");
    secondFile.setTitle("Manual");
    secondFile.setVersion("1");
    secondFile.setExtension("pdf");
    secondFile.setFileServerPath("/tmp/manual.pdf");
    secondFile.setFileLength(250L);
    secondFile.setFileType("pdf");
    secondFile.setMimeType("application/pdf");
    secondFile.setCreatedBy(1L);
    secondFile.setModifiedBy(1L);
    secondFile.setWebPath("/files/manual.pdf");
    FileItemRepository.save(secondFile);

    List<FileItem> allFiles = FileItemRepository.findAll(new FileSpecification(), new DataConstraints());
    assertEquals(2, allFiles.size());

    file.setTitle("Updated Notes");
    // file.setTags(new String[] {"updated"});
    FileItem updated = FileItemRepository.save(file);
    assertNotNull(updated);

    FileItem loaded = FileItemRepository.findById(file.getId());
    assertNotNull(loaded);
    assertEquals("Updated Notes", loaded.getTitle());
    // assertEquals("updated", loaded.getTags()[0]);
  }
}
