/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.simisinc.platform.infrastructure.persistence.cms;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.SQLException;
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.github.rajkowski.database.DataConstraints;
import com.simisinc.platform.domain.model.cms.WebPage;
import com.simisinc.platform.infrastructure.persistence.RepositoryDatabaseTestSupport;

class WebPageRepositoryTest {

  @BeforeEach
  void setUp() throws SQLException {
    RepositoryDatabaseTestSupport.configureInMemoryH2Database();
    RepositoryDatabaseTestSupport.executeSql(
        "CREATE TABLE web_pages ("
            + "web_page_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "link VARCHAR(255) NOT NULL,"
            + "redirect_url VARCHAR(255),"
            + "page_title VARCHAR(255),"
            + "page_keywords VARCHAR(255),"
            + "page_description TEXT,"
            + "draft BOOLEAN DEFAULT FALSE,"
            + "enabled BOOLEAN DEFAULT FALSE,"
            + "searchable BOOLEAN DEFAULT FALSE,"
            + "show_in_sitemap BOOLEAN DEFAULT FALSE,"
            + "created_by BIGINT NOT NULL,"
            + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "modified_by BIGINT NOT NULL,"
            + "role_id_list VARCHAR(255),"
            + "page_xml TEXT,"
            + "draft_page_xml TEXT,"
            + "comments TEXT,"
            + "page_image_url VARCHAR(255),"
            + "has_redirect BOOLEAN DEFAULT FALSE,"
            + "sitemap_priority DECIMAL(10, 3),"
            + "sitemap_changefreq VARCHAR(50),"
            + "tags JSONB,"
            + "page_text TEXT,"
            + "tsv OTHER"
            + ")");
  }

  @AfterEach
  void tearDown() {
    RepositoryDatabaseTestSupport.shutdown();
  }

  @Test
  void saveAndFindByLink() {
    WebPage page = new WebPage();
    page.setLink("/about");
    page.setTitle("About");
    page.setDescription("About our company");
    page.setDraft(false);
    page.setEnabled(true);
    page.setSearchable(true);
    page.setShowInSitemap(true);
    page.setCreatedBy(1L);
    page.setModifiedBy(1L);
    page.setPageXml("<page>about</page>");
    // page.setTags(new String[] {"company", "about"});

    WebPage saved = WebPageRepository.save(page);

    assertNotNull(saved);
    assertTrue(saved.getId() > 0);

    WebPage found = WebPageRepository.findByLink("/about");
    assertNotNull(found);
    assertEquals("About", found.getTitle());
    assertEquals("About our company", found.getDescription());
    assertTrue(found.getEnabled());
    assertTrue(found.getSearchable());
    assertTrue(found.getShowInSitemap());
  }

  @Test
  void updateAndFindAll() {
    WebPage page = new WebPage();
    page.setLink("/news");
    page.setTitle("News");
    page.setDescription("Latest updates");
    page.setDraft(false);
    page.setEnabled(false);
    page.setCreatedBy(1L);
    page.setModifiedBy(1L);
    page.setPageXml("<page>news</page>");
    WebPageRepository.save(page);

    WebPage secondPage = new WebPage();
    secondPage.setLink("/products");
    secondPage.setTitle("Products");
    secondPage.setDescription("Catalog");
    secondPage.setDraft(false);
    secondPage.setEnabled(true);
    secondPage.setCreatedBy(2L);
    secondPage.setModifiedBy(2L);
    secondPage.setPageXml("<page>products</page>");
    WebPageRepository.save(secondPage);

    List<WebPage> allPages = WebPageRepository.findAll(new WebPageSpecification(), new DataConstraints());
    assertEquals(2, allPages.size());

    page.setTitle("Updated News");
    page.setEnabled(true);
    page.setModifiedBy(3L);
    WebPage updated = WebPageRepository.save(page);

    assertNotNull(updated);
    WebPage loaded = WebPageRepository.findById(page.getId());
    assertNotNull(loaded);
    assertEquals("Updated News", loaded.getTitle());
    assertTrue(loaded.getEnabled());

    WebPage retained = WebPageRepository.findByLink("/products");
    assertNotNull(retained);
    assertEquals("Products", retained.getTitle());
  }
}
