/*
 * Copyright 2026 Matt Rajkowski (https://github.com/rajkowski)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.simisinc.platform.infrastructure.persistence.items;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.SQLException;
import java.sql.Timestamp;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.simisinc.platform.domain.model.items.Category;
import com.simisinc.platform.domain.model.items.Collection;
import com.simisinc.platform.domain.model.items.Item;
import com.simisinc.platform.domain.model.items.ItemFileItem;
import com.simisinc.platform.domain.model.items.ItemFileVersion;
import com.simisinc.platform.domain.model.items.ItemFolder;
import com.simisinc.platform.domain.model.items.ItemSubFolder;
import com.simisinc.platform.domain.model.items.Member;
import com.simisinc.platform.domain.model.items.PrivacyType;
import com.simisinc.platform.infrastructure.persistence.RepositoryDatabaseTestSupport;

class ItemsPersistenceRepositoryTest {

    @BeforeEach
    void setUp() throws SQLException {
        RepositoryDatabaseTestSupport.configureInMemoryH2Database();
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE collections ("
                        + "collection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "name VARCHAR(255) NOT NULL,"
                        + "unique_id VARCHAR(255) UNIQUE NOT NULL,"
                        + "description TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "category_count BIGINT DEFAULT 0,"
                        + "item_count BIGINT DEFAULT 0,"
                        + "allows_guests BOOLEAN DEFAULT FALSE,"
                        + "guest_privacy_type INTEGER DEFAULT 0,"
                        + "has_allowed_groups BOOLEAN DEFAULT FALSE,"
                        + "listings_link VARCHAR(255),"
                        + "image_url VARCHAR(255),"
                        + "header_xml TEXT,"
                        + "icon VARCHAR(255),"
                        + "show_listings_link BOOLEAN DEFAULT FALSE,"
                        + "show_search BOOLEAN DEFAULT FALSE,"
                        + "item_url_text VARCHAR(255),"
                        + "header_text_color VARCHAR(32),"
                        + "header_bg_color VARCHAR(32),"
                        + "menu_text_color VARCHAR(32),"
                        + "menu_bg_color VARCHAR(32),"
                        + "menu_border_color VARCHAR(32),"
                        + "menu_active_text_color VARCHAR(32),"
                        + "menu_active_bg_color VARCHAR(32),"
                        + "menu_active_border_color VARCHAR(32),"
                        + "menu_hover_text_color VARCHAR(32),"
                        + "menu_hover_bg_color VARCHAR(32),"
                        + "menu_hover_border_color VARCHAR(32),"
                        + "field_values TEXT,"
                        + "table_columns TEXT"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE collection_groups ("
                        + "allowed_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "collection_id BIGINT NOT NULL,"
                        + "group_id BIGINT NOT NULL,"
                        + "privacy_type INTEGER DEFAULT 0,"
                        + "view_all BOOLEAN DEFAULT TRUE,"
                        + "add_permission BOOLEAN DEFAULT FALSE,"
                        + "edit_permission BOOLEAN DEFAULT FALSE,"
                        + "delete_permission BOOLEAN DEFAULT FALSE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE lookup_collection_role ("
                        + "role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "collection_id BIGINT,"
                        + "code VARCHAR(255) NOT NULL,"
                        + "title VARCHAR(255),"
                        + "archived BOOLEAN DEFAULT FALSE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE collection_tabs ("
                        + "tab_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "collection_id BIGINT NOT NULL,"
                        + "tab_order INTEGER DEFAULT 0,"
                        + "name VARCHAR(255),"
                        + "link VARCHAR(255),"
                        + "page_title VARCHAR(255),"
                        + "page_keywords VARCHAR(255),"
                        + "page_description TEXT,"
                        + "page_image_url VARCHAR(255),"
                        + "draft BOOLEAN DEFAULT TRUE,"
                        + "enabled BOOLEAN DEFAULT TRUE,"
                        + "page_xml TEXT,"
                        + "role_id_list VARCHAR(255)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE categories ("
                        + "category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "collection_id BIGINT NOT NULL,"
                        + "unique_id VARCHAR(255),"
                        + "name VARCHAR(255) NOT NULL,"
                        + "description TEXT,"
                        + "icon VARCHAR(255),"
                        + "header_text_color VARCHAR(32),"
                        + "header_bg_color VARCHAR(32),"
                        + "item_url_text VARCHAR(255),"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "item_count BIGINT DEFAULT 0"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE items ("
                        + "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "collection_id BIGINT NOT NULL,"
                        + "category_id BIGINT DEFAULT -1,"
                        + "dataset_id BIGINT DEFAULT -1,"
                        + "unique_id VARCHAR(255),"
                        + "name VARCHAR(255),"
                        + "summary TEXT,"
                        + "description TEXT,"
                        + "description_text TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "location_name VARCHAR(255),"
                        + "street VARCHAR(255),"
                        + "address_line_2 VARCHAR(255),"
                        + "address_line_3 VARCHAR(255),"
                        + "city VARCHAR(255),"
                        + "state VARCHAR(255),"
                        + "country VARCHAR(255),"
                        + "postal_code VARCHAR(255),"
                        + "county VARCHAR(255),"
                        + "phone_number VARCHAR(255),"
                        + "email VARCHAR(255),"
                        + "cost DECIMAL(18,2),"
                        + "expected_date TIMESTAMP,"
                        + "start_date TIMESTAMP,"
                        + "end_date TIMESTAMP,"
                        + "expiration_date TIMESTAMP,"
                        + "url VARCHAR(255),"
                        + "url_text VARCHAR(255),"
                        + "image_url VARCHAR(255),"
                        + "barcode VARCHAR(255),"
                        + "keywords VARCHAR(255),"
                        + "archived_by BIGINT DEFAULT -1,"
                        + "archived TIMESTAMP,"
                        + "assigned_to BIGINT DEFAULT -1,"
                        + "assigned TIMESTAMP,"
                        + "approved_by BIGINT DEFAULT -1,"
                        + "approved TIMESTAMP,"
                        + "source VARCHAR(255),"
                        + "sync_date TIMESTAMP,"
                        + "dataset_key_value VARCHAR(255),"
                        + "geojson TEXT,"
                        + "tags VARCHAR(2048),"
                        + "field_values VARCHAR(2048),"
                        + "latitude DOUBLE DEFAULT 0,"
                        + "longitude DOUBLE DEFAULT 0,"
                        + "geom OTHER"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_categories ("
                        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "item_id BIGINT NOT NULL,"
                        + "category_id BIGINT NOT NULL,"
                        + "collection_id BIGINT NOT NULL,"
                        + "dataset_id BIGINT DEFAULT -1"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_folders ("
                        + "folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "item_id BIGINT NOT NULL,"
                        + "folder_unique_id VARCHAR(255),"
                        + "name VARCHAR(255),"
                        + "summary TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "file_count INTEGER DEFAULT 0,"
                        + "allow_guests BOOLEAN DEFAULT FALSE,"
                        + "allows_guests BOOLEAN DEFAULT FALSE,"
                        + "guest_privacy_type INTEGER DEFAULT 0,"
                        + "has_allowed_groups BOOLEAN DEFAULT FALSE,"
                        + "has_categories BOOLEAN DEFAULT FALSE,"
                        + "privacy_types VARCHAR(255),"
                        + "enabled BOOLEAN DEFAULT TRUE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_sub_folders ("
                        + "sub_folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "item_id BIGINT NOT NULL,"
                        + "folder_id BIGINT NOT NULL,"
                        + "name VARCHAR(255),"
                        + "summary TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "start_date TIMESTAMP,"
                        + "end_date TIMESTAMP,"
                        + "file_count INTEGER DEFAULT 0"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_folder_categories ("
                        + "category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "item_id BIGINT NOT NULL,"
                        + "folder_id BIGINT NOT NULL,"
                        + "name VARCHAR(255),"
                        + "enabled BOOLEAN DEFAULT TRUE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_folder_groups ("
                        + "allowed_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "item_id BIGINT NOT NULL,"
                        + "folder_id BIGINT NOT NULL,"
                        + "group_id BIGINT NOT NULL,"
                        + "privacy_type INTEGER DEFAULT 0,"
                        + "view_all BOOLEAN DEFAULT FALSE,"
                        + "add_permission BOOLEAN DEFAULT FALSE,"
                        + "edit_permission BOOLEAN DEFAULT FALSE,"
                        + "delete_permission BOOLEAN DEFAULT FALSE"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE members ("
                        + "member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "user_id BIGINT NOT NULL,"
                        + "item_id BIGINT NOT NULL,"
                        + "collection_id BIGINT NOT NULL,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "requested TIMESTAMP,"
                        + "approved_by BIGINT,"
                        + "approved TIMESTAMP,"
                        + "archived_by BIGINT,"
                        + "archived TIMESTAMP,"
                        + "last_viewed TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE member_roles ("
                        + "member_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "member_id BIGINT NOT NULL,"
                        + "user_id BIGINT NOT NULL,"
                        + "item_id BIGINT NOT NULL,"
                        + "role_id BIGINT NOT NULL,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_relationships ("
                        + "relationship_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "item_id BIGINT NOT NULL,"
                        + "collection_id BIGINT NOT NULL,"
                        + "related_item_id BIGINT NOT NULL,"
                        + "related_collection_id BIGINT NOT NULL,"
                        + "relationship_type BIGINT DEFAULT 0,"
                        + "is_active BOOLEAN DEFAULT TRUE,"
                        + "created_by BIGINT DEFAULT -1,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT DEFAULT -1,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "start_date TIMESTAMP,"
                        + "end_date TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_activity_stream ("
                        + "activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "item_id BIGINT NOT NULL,"
                        + "collection_id BIGINT NOT NULL,"
                        + "activity_type VARCHAR(255),"
                        + "message_text TEXT,"
                        + "source VARCHAR(255),"
                        + "source_link VARCHAR(255),"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "created_by BIGINT NOT NULL,"
                        + "modified_by BIGINT,"
                        + "modified TIMESTAMP"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_files ("
                        + "file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "item_id BIGINT NOT NULL,"
                        + "folder_id BIGINT NOT NULL,"
                        + "sub_folder_id BIGINT,"
                        + "category_id BIGINT,"
                        + "filename VARCHAR(255),"
                        + "title VARCHAR(255),"
                        + "barcode VARCHAR(255),"
                        + "version VARCHAR(100),"
                        + "extension VARCHAR(50),"
                        + "path VARCHAR(255),"
                        + "file_length BIGINT,"
                        + "file_type VARCHAR(50),"
                        + "mime_type VARCHAR(100),"
                        + "file_hash VARCHAR(255),"
                        + "width INTEGER DEFAULT -1,"
                        + "height INTEGER DEFAULT -1,"
                        + "summary TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT NOT NULL,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "processed TIMESTAMP,"
                        + "expiration_date TIMESTAMP,"
                        + "privacy_type INTEGER DEFAULT 0,"
                        + "default_token VARCHAR(255),"
                        + "version_count INTEGER DEFAULT 0,"
                        + "download_count BIGINT DEFAULT 0,"
                        + "web_path VARCHAR(255),"
                        + "tags VARCHAR(2048)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE item_file_versions ("
                        + "version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "file_id BIGINT NOT NULL,"
                        + "item_id BIGINT NOT NULL,"
                        + "folder_id BIGINT NOT NULL,"
                        + "sub_folder_id BIGINT,"
                        + "category_id BIGINT,"
                        + "filename VARCHAR(255),"
                        + "title VARCHAR(255),"
                        + "version VARCHAR(100),"
                        + "extension VARCHAR(50),"
                        + "path VARCHAR(255),"
                        + "file_length BIGINT,"
                        + "file_type VARCHAR(50),"
                        + "mime_type VARCHAR(100),"
                        + "file_hash VARCHAR(255),"
                        + "width INTEGER DEFAULT -1,"
                        + "height INTEGER DEFAULT -1,"
                        + "summary TEXT,"
                        + "created_by BIGINT NOT NULL,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "download_count BIGINT DEFAULT 0,"
                        + "web_path VARCHAR(255)"
                        + ")");
        RepositoryDatabaseTestSupport.executeSql(
                "CREATE TABLE collection_relationships ("
                        + "relationship_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + "collection_id BIGINT NOT NULL,"
                        + "related_collection_id BIGINT NOT NULL,"
                        + "relationship_type VARCHAR(255),"
                        + "is_active BOOLEAN DEFAULT TRUE,"
                        + "created_by BIGINT DEFAULT -1,"
                        + "created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
                        + "modified_by BIGINT DEFAULT -1,"
                        + "modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
                        + ")");
    }

    @AfterEach
    void tearDown() {
        RepositoryDatabaseTestSupport.shutdown();
    }

    @Test
    void collectionAndCategoryRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO collections (name, unique_id, description, created_by, allows_guests, guest_privacy_type, show_search, item_url_text) VALUES ('Catalog', 'catalog', 'Main catalog', 1, true, 0, true, 'item')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO collection_groups (collection_id, group_id, privacy_type, view_all, add_permission, edit_permission, delete_permission) VALUES (1, 9, 0, true, true, false, false)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO lookup_collection_role (collection_id, code, title) VALUES (1, 'owner', 'Owner')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO collection_tabs (collection_id, tab_order, name, link, page_title, enabled) VALUES (1, 1, 'Overview', '/overview', 'Overview', true)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO categories (collection_id, unique_id, name, description, created_by, item_url_text) VALUES (1, 'featured', 'Featured', 'Featured items', 1, 'featured')");

        Collection collection = CollectionRepository.findByUniqueId("catalog");
        assertNotNull(collection);
        assertEquals("Catalog", collection.getName());
        assertEquals(1, CollectionGroupRepository.findAllByCollectionId(collection.getId()).size());
        assertEquals("owner", CollectionRoleRepository.findByCode("owner").getCode());
        assertEquals(1, CollectionTabRepository.findAllByCollectionId(collection.getId()).size());

        Category category = CategoryRepository.findByNameWithinCollection("Featured", 1L);
        assertNotNull(category);
        assertEquals("featured", category.getUniqueId());
    }

    @Test
    void itemAndMemberRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO collections (name, unique_id, description, created_by) VALUES ('Catalog', 'catalog2', 'Secondary catalog', 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO categories (collection_id, unique_id, name, description, created_by) VALUES (1, 'news', 'News', 'Updates', 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO items (collection_id, category_id, unique_id, name, summary, created_by, modified_by, location_name, city, country, url, barcode, keywords, source, description, url_text) VALUES (1, 1, 'item-1', 'Widget', 'A widget', 1, 1, 'Headquarters', 'Austin', 'US', 'https://example.com', 'sku-1', 'widget', 'manual', 'Widget description', 'Visit')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_categories (item_id, category_id, collection_id, dataset_id) VALUES (1, 1, 1, -1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO members (user_id, item_id, collection_id, created_by, modified_by, approved_by, approved) VALUES (7, 1, 1, 1, 1, 1, CURRENT_TIMESTAMP)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO member_roles (member_id, user_id, item_id, role_id, created_by) VALUES (1, 7, 1, 3, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_relationships (item_id, collection_id, related_item_id, related_collection_id, relationship_type, is_active, created_by, modified_by) VALUES (1, 1, 1, 1, 9, true, 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_activity_stream (item_id, collection_id, activity_type, message_text, created_by) VALUES (1, 1, 'created', 'Item created', 1)");

        Item item = ItemRepository.findById(1L);
        assertNotNull(item);
        assertEquals("Widget", item.getName());
        assertEquals(1L, item.getCategoryId());
        assertEquals(1, ItemCategoryRepository.findAllByItemId(item.getId()).size());

        Member member = MemberRepository.findAllForUserId(7L).get(0);
        assertNotNull(member);
        assertEquals(1L, member.getItemId());
        assertTrue(MemberRepository.isApprovedMember(1L, 7L));
        assertEquals(1, MemberRoleRepository.findAllByUserIdAndItemId(7L, 1L).size());

        assertEquals(1, ItemRelationshipRepository.findRelatedItemsForItemId(1L).size());
        ActivitySpecification activitySpecification = new ActivitySpecification();
        activitySpecification.setItemId(1L);
        assertEquals("created", ActivityRepository.findAll(activitySpecification, null).get(0).getActivityType());
    }

    @Test
    void itemFolderAndFileRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO collections (name, unique_id, description, created_by) VALUES ('Catalog', 'catalog3', 'Third catalog', 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO items (collection_id, unique_id, name, created_by, modified_by) VALUES (1, 'item-2', 'Widget 2', 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_folders (item_id, folder_unique_id, name, summary, created_by, modified_by, allow_guests, guest_privacy_type, has_allowed_groups, has_categories, privacy_types) VALUES (1, 'visuals', 'Visuals', 'Images', 1, 1, true, 0, false, false, 'public')");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_sub_folders (item_id, folder_id, name, summary, created_by, modified_by) VALUES (1, 1, 'Gallery', 'Images', 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_folder_categories (item_id, folder_id, category_id) VALUES (1, 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_folder_groups (item_id, folder_id, group_id) VALUES (1, 1, 14)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_files (item_id, folder_id, filename, title, version, extension, path, file_length, file_type, mime_type, web_path, created_by, modified_by) VALUES (1, 1, 'image.png', 'Image', '1', 'png', '/tmp/image.png', 100, 'png', 'image/png', '/files/image.png', 1, 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO item_file_versions (file_id, item_id, folder_id, filename, title, version, extension, path, file_length, file_type, mime_type, web_path, created_by) VALUES (1, 1, 1, 'image.png', 'Image', '1', 'png', '/tmp/image.png', 100, 'png', 'image/png', '/files/image.png', 1)");

        ItemFolder folder = ItemFolderRepository.findByUniqueId("visuals", 1L);
        assertNotNull(folder);
        assertEquals("Visuals", folder.getName());
        assertEquals(1, ItemFolderCategoryRepository.findAllByFolderId(folder.getId()).size());
        assertEquals(1, ItemFolderGroupRepository.findAllByFolderId(folder.getId()).size());

        ItemSubFolder subFolder = ItemSubFolderRepository.findById(1L);
        assertNotNull(subFolder);
        assertEquals("Gallery", subFolder.getName());

        ItemFileItem file = ItemFileItemRepository.findByWebPath(1L, "/files/image.png");
        assertNotNull(file);
        assertEquals("Image", file.getTitle());

        ItemFileVersion fileVersion = ItemFileVersionRepository.findById(1L);
        assertNotNull(fileVersion);
        assertEquals("Image", fileVersion.getTitle());
    }

    @Test
    void repositories_saveRecords() {
        Collection collection = new Collection();
        collection.setName("Saved Catalog");
        collection.setUniqueId("saved-catalog");
        collection.setDescription("Catalog created through repository.save");
        collection.setCreatedBy(1L);
        collection.setGuestPrivacyType(PrivacyType.PUBLIC);

        Collection savedCollection = CollectionRepository.save(collection);
        assertNotNull(savedCollection);
        assertTrue(savedCollection.getId() > 0);

        collection.setName("Updated Catalog");
        Collection updatedCollection = CollectionRepository.save(collection);
        assertNotNull(updatedCollection);
        assertEquals("Updated Catalog", CollectionRepository.findById(collection.getId()).getName());

        Category category = new Category();
        category.setCollectionId(savedCollection.getId());
        category.setUniqueId("saved-category");
        category.setName("Saved Category");
        category.setDescription("Category created in the save test");
        category.setCreatedBy(1L);
        Category savedCategory = CategoryRepository.save(category);
        assertNotNull(savedCategory);
        assertTrue(savedCategory.getId() > 0);

        Item item = new Item();
        item.setCollectionId(savedCollection.getId());
        item.setCategoryId(savedCategory.getId());
        item.setCategoryIdList(new Long[] { savedCategory.getId() });
        item.setUniqueId("saved-item");
        item.setName("Saved Widget");
        item.setSummary("Summary for the saved item");
        item.setDescription("Description of the saved item");
        item.setCreatedBy(1L);
        item.setModifiedBy(1L);
        item.setSource("manual");

        Item savedItem = ItemRepository.save(item);
        assertNotNull(savedItem);
        assertTrue(savedItem.getId() > 0);

        item.setName("Updated Widget");
        item.setCategoryIdList(new Long[] { savedCategory.getId() });
        item.setModifiedBy(2L);
        Item updatedItem = ItemRepository.save(item);
        assertNotNull(updatedItem);
        assertEquals("Updated Widget", ItemRepository.findById(item.getId()).getName());

        Member member = new Member();
        member.setUserId(99L);
        member.setItemId(savedItem.getId());
        member.setCollectionId(savedCollection.getId());
        member.setCreatedBy(1L);
        member.setModifiedBy(1L);
        member.setApprovedBy(1L);
        member.setApproved(new Timestamp(System.currentTimeMillis()));

        Member savedMember = MemberRepository.save(member);
        assertNotNull(savedMember);
        assertTrue(savedMember.getId() > 0);
        assertTrue(MemberRepository.isApprovedMember(savedItem.getId(), 99L));

        ItemFolder folder = new ItemFolder();
        folder.setItemId(savedItem.getId());
        folder.setUniqueId("saved-folder");
        folder.setName("Saved Folder");
        folder.setSummary("Folder saved through repository");
        folder.setCreatedBy(1L);
        folder.setModifiedBy(1L);
        folder.setGuestPrivacyType(PrivacyType.PUBLIC);

        ItemFolder savedFolder = ItemFolderRepository.save(folder);
        assertNotNull(savedFolder);
        assertTrue(savedFolder.getId() > 0);

        folder.setName("Updated Folder");
        folder.setModifiedBy(3L);
        ItemFolder updatedFolder = ItemFolderRepository.save(folder);
        assertNotNull(updatedFolder);
        assertEquals("Updated Folder", ItemFolderRepository.findById(folder.getId()).getName());
    }

    @Test
    void collectionRelationshipAndActivityRepositories_findRecords() throws SQLException {
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO collections (name, unique_id, description, created_by) VALUES ('Catalog One', 'catalog-one', 'One', 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO collections (name, unique_id, description, created_by) VALUES ('Catalog Two', 'catalog-two', 'Two', 1)");
        RepositoryDatabaseTestSupport.executeSql(
                "INSERT INTO collection_relationships (collection_id, related_collection_id, relationship_type) VALUES (1, 2, 'recommended')");

        assertEquals(1, CollectionRelationshipRepository.findAllChildrenByCollectionId(1L).size());
        assertEquals(1L, CollectionRelationshipRepository.findAllParentsByCollectionId(2L).get(0).getCollectionId());
    }
}
